version: 2

my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ngmltoh-rf00795
    
      # User/password auth
      user: stijndlphn
      password: Keberuntungan4!

      role: accountadmin
      database: PC_DBT_DB
      warehouse: PC_DBT_WH
      schema: PC_DBT_SCHEMA
      threads: 1
      client_session_keep_alive: False
      query_tag: sd

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)