version: 2

slprofile:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: fc65562
      user: Stijndlphn
      password: Keberuntungan4!
      database: PC_DBT_DB
      schema: PC_DBT_SCHEMA
      role: accountadmin
      warehouse: PC_DBT_WH
      threads: 1
      client_session_keep_alive: False
      query_tag: sd